version: "2"
services:
  node:
    image: "node:lts"
    user: "node"
    restart: always
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: >
      sh -c   "npm install &&
              npm run app"
